name: Pull Request CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: make deps

      - name: Install linting tools
        run: make lint-install

      - name: Run full linting
        run: make lint

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Install ArgoCD
        run: make install-argocd generate-env

      - name: Run tests
        run: |
          source .env
          make test

      - name: Run tests with coverage
        run: make test-cover

      - name: Build binary
        run: make build
